### ISSUE TITLE
Daemon process throws errors for 3rd party transforms

### ISSUE THREAD

**Issue by muralikr** [yahoo/mendel#127]
After recent changes to https://github.com/yahoo/mendel/blob/master/packages/mendel-config/src/transform-config.js file, daemon is throwing errors at this line: https://github.com/yahoo/mendel/blob/master/packages/mendel-pipeline/src/transformer/worker.js#L18

```
[Pipeline] "IndependentSourceTransform" errored:
Errored while transforming ./src/components/body.jsx: Transform foo-bar is incompatible with Mendel.
Error: Transform foo-bar is incompatible with Mendel.
    at promise.then.then (/Users/user1/mendel/packages/mendel-pipeline/src/transformer/worker.js:18:31)
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

Expected plugin type: `function`
Actual plugin type: `object`

As of now, `full-example` has `json-parse` transform which is not used. Hence, we couldn't catch this error during testing.

@irae @stephanwlee

**Comment by irae** [comment]
Can you clarify which version of npm package you are using or if you are running against master?

I do use `mendel-parser-json` as `json-parse` same as in `full-example/.mendelrc` and I don't have this issue. Are you sure you updated all things?

A simple way to be sure what you are running is the following:

```bash
npm ls | grep mendel
```

**Comment by muralikr** [comment]
I am running application with master branch. After [reverting](https://github.com/yahoo/mendel/commit/b6a67e55882f06a4cd5903d6b2e4974788b19ac5) `transform-config` file changes, daemon process is working fine.

**Comment by irae** [comment]
for reference, here is what I think is really stable for me. After a couple of days of cleaning bugs and finding package.json issues, I finally think we have a good candidate:

```
$ npm ls | grep mendel
├─┬ mendel-development-middleware@3.1.2
│ ├─┬ mendel-config@3.1.1
│ ├─┬ mendel-development@3.0.0
│ ├─┬ mendel-exec@3.0.1
│ ├─┬ mendel-pipeline@3.1.3
│ │ ├── mendel-config@3.1.1 deduped
│ │ ├── mendel-deps@3.1.0 deduped
│ │ ├── mendel-development@3.0.0 deduped
│ │ ├── mendel-resolver@3.0.2 deduped
├─┬ mendel-generator-prune@3.0.1
├─┬ mendel-middleware@3.0.4
│ ├─┬ mendel-core@3.0.3
│ │ ├─┬ mendel-config@3.1.1
│ ├── mendel-loader@3.0.0
├─┬ mendel-outlet-browser-pack@3.1.0
├─┬ mendel-outlet-manifest@3.0.3
│ ├─┬ mendel-manifest-uglify@3.0.2
├── mendel-parser-json@3.0.0
├─┬ mendel-pipeline@3.1.3
│ ├─┬ mendel-config@3.1.1
│ ├─┬ mendel-deps@3.1.0
│ ├── mendel-development@3.0.0 deduped
│ ├─┬ mendel-resolver@3.0.2
│ │ └── mendel-development@3.0.0 deduped
├─┬ mendel-transform-buble@1.0.1
```

**Comment by irae** [comment]
It also works for me if I link everything.

**Comment by irae** [comment]
```
$ cat package.json | grep mendel
    "build": "NODE_ENV=production mendel --outlet",
    "watcher": "mendel --watch",
    "mendel-middleware": "^3.0.4",
    "mendel-development-middleware": "^3.1.2",
    "mendel-generator-prune": "^3.0.1",
    "mendel-outlet-browser-pack": "^3.1.0",
    "mendel-outlet-manifest": "^3.0.3",
    "mendel-parser-json": "^3.0.0",
    "mendel-pipeline": "^3.1.3",
    "mendel-transform-buble": "^1.0.1",
```

**Comment by irae** [comment]
only production dependency is "mendel-middleware": "^3.0.4",

**Comment by muralikr** [comment]
Issue was resolved after adding `mode` field in our custom transformer's package.json. Earlier, `mode` is set from exported module. Moved this to `package.json`.

**Comment by irae** [comment]
All is well when it ends well =)
