### ISSUE TITLE
npm link all unable to link specific package mendel-full-example

### ISSUE THREAD

**Issue by kluzny** [yahoo/mendel#60]
Having some issues run the master `npm run linkall` and `npm unit test` see below: 

In general should I expect a green build? 

`npm run linkall`
........
local install mendel-full-example ...
npm ERR! Darwin 16.1.0
npm ERR! argv "/Users/kyle/.nvm/versions/node/v5.0.0/bin/node" "/Users/kyle/.nvm/versions/node/v5.0.0/bin/npm" "install"
npm ERR! node v5.0.0
npm ERR! npm  v3.3.6
npm ERR! code E404

npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/karma-mendel
npm ERR! 404
npm ERR! 404 'karma-mendel' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'mendel-full-example'
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/kyle/Development/mendel/examples/full-example/npm-debug.log
local install mendel-full-example ...

[npm-debug.log.txt](https://github.com/yahoo/mendel/files/614183/npm-debug.log.txt)

I think this is causing my `npm test` to fail as well: 

`npm run unit`
.....
test/tree-hash-walker.js ............................ 15/15
test/tree-serializer.js ............................... 9/9
test/tree-variation-walker-server.js .................. 3/3
test/tree-variation-walker.js ......................... 9/9
test/tree-walker.js ................................... 7/7
test/trees.js ....................................... 15/15
Bail out! # should create manifest but failed

npm ERR! Darwin 16.1.0
npm ERR! argv "/Users/kyle/.nvm/versions/node/v5.0.0/bin/node" "/Users/kyle/.nvm/versions/node/v5.0.0/bin/npm" "run" "unit"
npm ERR! node v5.0.0
npm ERR! npm  v3.3.6
npm ERR! code ELIFECYCLE
npm ERR! mendel-monorepo@ unit: `DEBUG='' tap test/*.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mendel-monorepo@ unit script 'DEBUG='' tap test/*.js'.
npm ERR! This is most likely a problem with the mendel-monorepo package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     DEBUG='' tap test/*.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls mendel-monorepo
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/kyle/Development/mendel/npm-debug.log

[npm-debug.log.txt](https://github.com/yahoo/mendel/files/614184/npm-debug.log.txt)

**Comment by kluzny** [comment]
I just noticed the 'For the moment, Mendel relies on some private repository' so please let me know if I shouldn't worry about those errors

**Comment by irae** [comment]
First, about `npm run linkall`: TBH, NPM is changing a bit too fast. In node 6.5 with the npm that ships with this version, `npm run linkall` just works. Something might be wrong with `karma-mendel`, but everything else should be fine. Yesterday I started developing on 6.9 and I am having the same issues that you pointed out. I need to take a look. PR also welcome :)

Right now Mendel is a bit unstable... we decided to make it like that for a while since keeping branches are too costly since we don't have a lot of consumers yet. The repo is in a bad state but all the NPM  packages are fine. If you are interested into taking a look at a clean state I'll create a tag and post it here.

Sorry about that.

**Comment by irae** [comment]
Here you go, stable tag: https://github.com/yahoo/mendel/tree/stable

**Comment by kluzny** [comment]
Sounds good, I will use npm 6.5 and stable as a baseline ( at least until 2.0 drops soon ish )

**Comment by irae** [comment]
Hey, I'll live it open, actually. I want to fix this. 😉 

Otherwise I might forget

**Comment by irae** [comment]
@kluzny I fixed not only the `linkall` problem but also fixed the tests. The repo should be healthy again. `master` now contains both WIP for mendel-v2 and stable mendel-v1 without known issues.
