### ISSUE TITLE
[Spike] Test bundler building for test frameworks like karma

### ISSUE THREAD

**Issue by stephanwlee** [yahoo/mendel#77]

**Comment by stephanwlee** [comment]
Mocha support is on the way. We may not support karma ourselves.

**Comment by stephanwlee** [comment]
Mocha is supported via mocha runner. Instead of mocha watching and running file, mendel is in control and evaluates javascript from in-memory sources.

**Comment by irae** [comment]
Is it like SUPA FAST? or is it just faster? 😉

**Comment by stephanwlee** [comment]
you can try it by using `npm t` on the full-example package.

**Comment by irae** [comment]
I don't have a project with working unit test and Mendel 1 and working unit test on Mendel 2... you have it, thats why I asked. 😜
