### ISSUE TITLE
Fault Tolerance

### ISSUE THREAD

**Issue by jamesalley** [yahoo/mendel#83]
If a file is saved with, say, an undefined variable in it, it will cause the daemon to exit. It's pretty routine to write code, save, and repeat several times before looking at the result in the browser, so this failure can occur frequently. 

It would be nice if the daemon could restart itself. Of course, if the error is still present it will fail again, and we don't want it to just endlessly start/stop.

Maybe we could play a chime, beep, or even execute 'say "Daemon stopped. Will attempt to restart in one minute."' which in mac os terminal will make a verbal announcement. Then at least the problem of "keeping an eye on the daemon" would be mitigated.

**Comment by irae** [comment]
Thanks for the report!

The fact that the daemon exits is a bug.

I think the right way to deal with this is to log in red or some way that is noticeable on the deamon process. Another option or configuration could be to compile a bundle that display the error on the browser. This way people see the error right away even if the deamon is running as a service (which is something we wish for the future).

The deamon should never crash or need restart. The code you are writing is not mendel code, so mendel should not stop working, it should give you the information in the best way possible.

**Comment by stephanwlee** [comment]
@jamesalley and @irae Hello all!

Yeah, it was a deliberate choice to crash it for now as I had no idea what to do ATM in case of error. I will probably, in next two weeks, make changes so it alerts client and client decides what to do with the error (in addition to some stderr on the daemon side)
